"""add branch to student profile

Revision ID: 792c11d80fdf
Revises: 07c27432ddfb
Create Date: 2026-09-22 22:49:18.367825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792c11d80fdf'
down_revision = '07c27432ddfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('branch')

    # ### end Alembic commands ###
